name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.13.0
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install

      - name: Build Core
        run: npm run build -w @discoui-org/core

      - name: Build Vue SDK
        run: npm run build -w @discoui-org/vue

      - name: Build Capacitor Plugin
        run: npm run build -w @discoui-org/capacitor
